<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>88750cad-f9e9-4d55-b566-378c5627c9f3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Denali.Processors\Denali.Processors.csproj" />
    <ProjectReference Include="..\Denali.Services\Denali.Services.csproj" />
    <ProjectReference Include="..\Denali.TechnicalAnalysis\Denali.TechnicalAnalysis.csproj" />
  </ItemGroup>

</Project>
